require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RecordsController, type: :controller do

  let(:zone) { Zone.create(zone: 'example.com') }

  # This should return the minimal set of attributes required to create a valid
  # Record. As you add validations to Record, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { type_of: 'TXT', rdata: 'test', zone_id: zone.id }
  }

  let(:invalid_attributes) {
    { type_of: 'CERT', rdata: 'test' }
  }

  let(:valid_params) {
    { zone_id: zone.id, record: { type_of: 'TXT', rdata: 'test' } }
  }

  let(:invalid_params) {
    { zone_id: zone.id, record: { type_of: 'CERT', rdata: 'test' } }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:ns1_success) do
    Typhoeus::Response.new(
      code: 200,
      return_code: :ok,
      body: { id: '5d97d992403d5d000156f081', ttl: 3600 }.to_json
    )
  end

  let(:ns1_failure) do
    Typhoeus::Response.new(
      code: 500,
      body: { message: 'Something went wrong' }.to_json
    )
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: { zone_id: zone.id }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      zone = Record.create! valid_attributes
      get :edit, params: {id: zone.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context 'when the NS1 request is successful' do
      before do
        allow(Ns1::Record).to receive(:create)
          .and_return(ns1_success)
      end

      context "with valid params" do
        it "creates a new Record" do
          expect {
            post :create, params: valid_params, session: valid_session
          }.to change(Record, :count).by(1)
        end

        it "redirects to the created record" do
          post :create, params: valid_params, session: valid_session
          expect(response).to redirect_to(zone)
        end
      end

      context "with invalid params" do
        it "returns a success response" do
          post :create, params: invalid_params, session: valid_session
          expect(response).to be_successful
        end
      end
    end

    context 'when NS1 returns an error' do
      before do
        allow(Ns1::Record).to receive(:create)
          .and_return(ns1_failure)
      end

      it 'redirects to the form' do
        post :create, params: valid_params, session: valid_session
        expect(response).to redirect_to(new_record_path)
      end

      it 'displays an error message to the user' do
        post :create, params: valid_params, session: valid_session
        expect(flash[:notice]).to match(/try again/)
      end
    end
  end

  describe "PUT #update" do
    context 'when the NS1 request is successful' do
      before do
        allow(Ns1::Record).to receive(:update)
          .and_return(ns1_success)
      end

      context "with valid params" do
        let(:record) { Record.create! valid_attributes }
        let(:new_params) {
          { id: record.to_param, zone_id: zone.id, record: { type_of: 'TXT', rdata: 'test1' } }
        }

        it "updates the requested record" do
          put :update, params: new_params, session: valid_session
          record.reload
          expect(record.rdata).to eq 'test1'
        end

        it "redirects to the zone" do
          put :update, params: new_params, session: valid_session
          expect(response).to redirect_to(zone)
        end
      end

      context "with invalid params" do
        it "returns a success response (i.e. to display the 'edit' template)" do
          record = Record.create! valid_attributes
          put :update, params: {id: record.to_param, record: invalid_attributes}, session: valid_session
          expect(response).to be_successful
        end
      end
    end

    context 'when NS1 returns an error' do
      let(:record) { Record.create! valid_attributes }
      before do
        allow(Ns1::Record).to receive(:update)
          .and_return(ns1_failure)
      end

      it 'redirects to the form' do
        put :update, params: {id: record.to_param, record: valid_attributes}, session: valid_session
        expect(response).to redirect_to(edit_record_path(record))
      end

      it 'displays an error message to the user' do
        put :update, params: {id: record.to_param, record: valid_attributes}, session: valid_session
        expect(flash[:notice]).to match(/try again/)
      end
    end
  end

  describe "DELETE #destroy" do
    let!(:record) { Record.create! valid_attributes }
    let(:ns1_success) do
      Typhoeus::Response.new(
        code: 200,
        return_code: :ok,
        body: {}.to_json
      )
    end

    let(:ns1_failure) do
      Typhoeus::Response.new(
        code: 404,
        return_code: :ok,
        body: { message: 'record not found' }.to_json
      )
    end

    context 'when the NS1 request is successful' do
      before do
        allow(Ns1::Record).to receive(:destroy)
          .and_return(ns1_success)
      end

      it "destroys the requested record" do
        expect {
          delete :destroy, params: {id: record.to_param}, session: valid_session
        }.to change(Record, :count).by(-1)
      end

      it "redirects to the zone show page" do
        delete :destroy, params: {id: record.to_param}, session: valid_session
        expect(response).to redirect_to(record.zone)
      end
    end

    context 'when NS1 returns an error' do
      before do
        allow(Ns1::Record).to receive(:destroy)
          .and_return(ns1_failure)
      end

      let(:back) { zones_url + "/#{zone.id}" }
      before { request.env['HTTP_REFERER'] = back }

      it 'redirects back' do
        delete :destroy, params: { id: record.to_param }, session: valid_session
        expect(response).to redirect_to(back)
      end

      it 'displays an error message to the user' do
        delete :destroy, params: { id: record.to_param }, session: valid_session
        expect(flash[:notice]).to match(/try again/)
      end

      context 'when redirecting back is not an option' do
        before { request.env['HTTP_REFERER'] = nil }

        it 'redirects to /records' do
          delete :destroy, params: { id: record.to_param }, session: valid_session
          expect(response).to redirect_to(zones_url)
        end
      end
    end
  end
end
